import assert from 'node:assert/strict';
import { CalendarView } from '../src/pages/CalendarPage';
import { CourseTypeField, CreateAssignmentForm, CreateQuizForm } from '../src/pages/FacultyDashboard';
import { courseCategory } from '../src/pages/StudentDashboard';
import { ScheduleForm, ScheduledClassList } from '../src/pages/SchedulePage';
import { ClassHistory, nextScheduledPlan, shouldShowCourseHero } from '../src/pages/FacultyCoursePage';
import { studentMaterialGroups } from '../src/pages/StudentCoursePage';
import { dayKey, groupEvents, monthDays, monthRange } from '../src/components/dashboard/calendarDates';
import { institutionHost, institutionHeaders } from '../src/api/institutionHost';
import { apiFetch, login as requestLogin, createFaculty } from '../src/api/client';
import { brand, BrandLogo, pageTitle } from '../src/branding/Brand';
import Login from '../src/pages/login';
import GoogleSignIn, { loadGoogleIdentity } from '../src/components/GoogleSignIn';
import { AuthProvider } from '../src/context/AuthContext';
import { ThemeProvider } from '../src/context/ThemeContext';
import InstitutionRegistration from '../src/pages/InstitutionRegistration';
import AccountRegistrationForm from '../src/components/dashboard/AccountRegistrationForm';
import AccountEditor from '../src/components/dashboard/AccountEditor';
import ERPIntegration, { ERPUserImportPreview } from '../src/components/dashboard/ERPIntegration';
import { ActionCard, BulkAccountsPanel, CgpaPlannerPanel, CourseKnowledgePanel, FacultyContentDraftPanel, ProgressInsightsPanel, bulkCsvTemplate, parseBulkCsv } from '../src/pages/AIAssistantPage';
import ForgotPasswordPage from '../src/pages/ForgotPasswordPage';
import ResetPasswordPage from '../src/pages/ResetPasswordPage';
import LectureNotesPanel, { LectureReviewControls, preparationLabel } from '../src/components/dashboard/LectureNotesPanel';
import ProgrammingAssessmentForm from '../src/components/dashboard/ProgrammingAssessmentForm';
import { renderToStaticMarkup } from 'react-dom/server';
import { StaticRouter } from 'react-router-dom/server';
import { Routes, Route, matchRoutes } from 'react-router-dom';
import DashboardShell from '../src/components/dashboard/DashboardShell';
import { dashboardNavigation, dashboardPath, isDashboardPage, studentPortalSections, studentSectionForPage } from '../src/components/dashboard/navigation';

let count = 0;
assert.ok(isDashboardPage('student', 'timetable'));
assert.ok(isDashboardPage('student', 'subject-enrollment'));
assert.ok(dashboardNavigation.student.some(item => item.id === 'subject-enrollment' && item.label === 'Enroll Subjects'));
assert.equal(isDashboardPage('student', 'calendar'), false);
for (const role of ['faculty', 'hod']) assert.ok(isDashboardPage(role, 'calendar'));
assert.equal(isDashboardPage('admin', 'calendar'), false);
assert.equal(monthDays(new Date(2024, 1, 1)).length, 35);
assert.equal(monthDays(new Date(2026, 1, 1)).length, 35);
assert.equal(monthDays(new Date(2026, 2, 1)).length, 42);
const range = monthRange(new Date(2026, 11, 15));
assert.equal(dayKey(new Date(range.start)), '2026-12-01');
assert.equal(dayKey(new Date(range.end)), '2027-01-01');
const calendarProps = { month: new Date(2026, 8, 1), selected: new Date(2026, 8, 4), events: [], loading: false, error: '', onMonth() {}, onSelect() {}, onRetry() {}, role: 'student' };
assert.ok(renderToStaticMarkup(<CreateAssignmentForm courses={[]} onCreated={() => {}} />).includes('type="datetime-local"'));
const courseTypeField = renderToStaticMarkup(<CourseTypeField value="academic" onChange={() => {}} />);
assert.ok(courseTypeField.includes('Course type') && courseTypeField.includes('Academic') && courseTypeField.includes('Non-Academic'));
assert.equal(courseCategory({course_type:'non_academic'}), 'non_academic');
assert.equal(courseCategory({course_type:'academic'}), 'academic');
assert.equal(courseCategory({}), 'academic');
const fixedCourse = {id:7,code:'C7',name:'Specific course'};
const fixedAssignment = renderToStaticMarkup(<CreateAssignmentForm courses={[fixedCourse]} fixedCourse={fixedCourse} onCreated={() => {}} />);
assert.ok(fixedAssignment.includes('C7 · Specific course'));
assert.ok(!fixedAssignment.includes('<select'));
const fixedQuiz = renderToStaticMarkup(<CreateQuizForm courses={[fixedCourse]} fixedCourse={fixedCourse} onCreated={() => {}} />);
assert.ok(fixedQuiz.includes('C7 · Specific course'));
assert.ok(!fixedQuiz.includes('<select'));
assert.ok(!dashboardNavigation.faculty.some(item => ['assignments','quizzes'].includes(item.id)));
const scheduleForm = renderToStaticMarkup(<StaticRouter><ScheduleForm courses={[{id:1,code:'T1',name:'Test course'}]} onSubmit={() => {}} busy={false} /></StaticRouter>);
assert.ok(scheduleForm.includes('type="datetime-local"') && scheduleForm.includes('Students can join only after'));
const fixedSchedule = renderToStaticMarkup(<StaticRouter><ScheduleForm courses={[fixedCourse]} fixedCourse={fixedCourse} onSubmit={() => {}} busy={false} /></StaticRouter>);
assert.ok(fixedSchedule.includes('C7 · Specific course') && !fixedSchedule.includes('<select'));
const scheduleList = renderToStaticMarkup(<StaticRouter><ScheduledClassList plans={[{id:1,status:'scheduled',title:'Test class',course_code:'T1',course_name:'Test course',starts_at:'2030-01-01T10:00:00Z'}]} busy={false} onStart={() => {}} onCancel={() => {}} /></StaticRouter>);
assert.ok(scheduleList.includes('Start class') && scheduleList.includes('Cancel schedule'));
const endedScheduleList = renderToStaticMarkup(<StaticRouter><ScheduledClassList plans={[{id:2,status:'ended',title:'Ended class',course_code:'T1',course_name:'Test course',starts_at:'2030-01-01T10:00:00Z'}]} busy={false} onStart={() => {}} onCancel={() => {}} /></StaticRouter>);
assert.ok(!endedScheduleList.includes('Start class') && !endedScheduleList.includes('Rejoin class'));
const classHistory = renderToStaticMarkup(<ClassHistory sessions={[{id:2,scheduled_at:'2030-01-01T10:00:00Z',ended_at:'2030-01-01T11:15:00Z'}]} />);
assert.ok(classHistory.includes('Class history') && classHistory.includes('75 minutes'));
assert.ok(!classHistory.includes('Start class') && !classHistory.includes('Join now') && !classHistory.includes('Rejoin'));
assert.equal(shouldShowCourseHero([]), true);
assert.equal(shouldShowCourseHero([{id:1,ended_at:null}]), true);
assert.equal(shouldShowCourseHero([{id:1,ended_at:'2030-01-01T11:15:00Z'}]), false);
assert.equal(shouldShowCourseHero([{id:1,ended_at:'2030-01-01T11:15:00Z'},{id:2,ended_at:null}]), true);
const scheduledPlans = [{id:2,status:'scheduled',starts_at:'2030-01-02T10:00:00Z'},{id:1,status:'scheduled',starts_at:'2030-01-01T10:00:00Z'},{id:3,status:'live',starts_at:'2029-01-01T10:00:00Z'}];
assert.equal(nextScheduledPlan(scheduledPlans).id, 1);
assert.equal(shouldShowCourseHero([{id:1,ended_at:'2030-01-01T11:15:00Z'}], scheduledPlans), true);
const calendarHtml = props => renderToStaticMarkup(<StaticRouter><CalendarView {...calendarProps} {...props} /></StaticRouter>);
assert.ok(calendarHtml().includes('No dated events this month.'));
assert.ok(calendarHtml().includes('Previous month'));
assert.ok(calendarHtml().includes('Daily agenda'));
assert.ok(!calendarHtml({loading: true}).includes('No dated events this month.'));
assert.ok(calendarHtml({error: 'Test load failure'}).includes('role="alert"'));
const isolatedEvent = {id: 'assignment-1', kind: 'assignment', title: '<script>test</script>', course_code: 'TEST', course_name: 'Test course', starts_at: new Date(2026, 8, 4, 10).toISOString()};
assert.equal(groupEvents([isolatedEvent])['2026-09-04'].length, 1);
assert.ok(calendarHtml({events: [isolatedEvent]}).includes('&lt;script&gt;'));
assert.ok(calendarHtml({events: [isolatedEvent]}).includes('href="/student/academic-assignments"'));
assert.ok(calendarHtml({events: [isolatedEvent], role: 'hod'}).includes('href="/hod/courses"'));
assert.ok(!calendarHtml({events: [isolatedEvent], role: 'hod'}).includes('href="/hod/assignments"'));
const plannedEvent = {...isolatedEvent,id:'scheduled-1',kind:'class',status:'scheduled',title:'Planned class'};
assert.ok(calendarHtml({events:[plannedEvent],role:'faculty'}).includes('Manage schedule'));
assert.ok(calendarHtml({events:[plannedEvent],role:'faculty'}).includes('href="/faculty/schedule"'));
console.log('PASS calendar dates, month/year boundaries, empty/loading/error states, escaped content and role links');
for (const [role, items] of Object.entries(dashboardNavigation)) {
  const pattern = `/${role}/:page?`;
  assert.equal(new Set(items.map(item => item.id)).size, items.length);
  assert.equal(dashboardPath(role), `/${role}`);
  for (const item of items) {
    const pathname = dashboardPath(role, item.id);
    const route = matchRoutes([{ path: pattern }], pathname);
    assert.ok(route, `Direct route ${pathname}`);
    assert.equal(route[0].params.page || 'dashboard', item.id);
    assert.ok(isDashboardPage(role, item.id));
    const html = renderToStaticMarkup(
      <StaticRouter location={pathname}>
        <Routes><Route path={pattern} element={
          <DashboardShell user={{ name: 'Isolated Test', role }} title="LMS" roleLabel={role} onLogout={() => {}}>
            <p>Current page content</p>
          </DashboardShell>
        } /></Routes>
      </StaticRouter>
    );
    assert.equal((html.match(/aria-current="page"/g) || []).length, 1, 'One active sidebar item');
    assert.ok(html.includes('id="portal-navigation"'));
    assert.ok(html.includes('aria-controls="portal-navigation"'));
    assert.ok(html.includes('aria-label="Close left menu"'));
    assert.ok(html.includes('sidebar-collapse-toggle'));
    assert.ok(!html.includes('mobile-menu'));
    assert.match(html, new RegExp(`aria-current="page"[^>]*href="${pathname}"`));
    const expectedSidebarItems = role === 'student' ? studentSectionForPage(item.id).items : items;
    for (const other of expectedSidebarItems) assert.ok(html.includes(`href="${dashboardPath(role, other.id)}"`));
    if (role === 'student') {
      for (const section of studentPortalSections) {
        assert.ok(html.includes(`href="${dashboardPath(role, section.entry)}"`));
        assert.ok(html.includes(`>${section.label}</a>`));
      }
      assert.ok(html.includes(`>${studentSectionForPage(item.id).label}</span>`));
    }
    assert.equal(html.includes('href="#'), false, 'No scroll-only sidebar or brand links');
    if (item.id !== 'dashboard') assert.ok(html.includes(`<h1>${item.label}</h1>`));
    assert.ok(html.includes('Current page content'));
    count++;
  }
  assert.equal(isDashboardPage(role, 'not-a-page'), false);
  assert.equal(matchRoutes([{ path: pattern }], `/${role}/courses/extra`), null);
  for (const otherRole of Object.keys(dashboardNavigation).filter(value => value !== role)) {
    assert.equal(matchRoutes([{ path: pattern }], `/${otherRole}/register-faculty`), null);
  }
}
assert.equal(isDashboardPage('student', 'register-faculty'), false);
assert.equal(isDashboardPage('faculty', 'register-student'), false);
assert.ok(dashboardNavigation.admin.some(item => item.id === 'register-student'));
assert.equal(isDashboardPage('unknown'), false);
const facultyCourseRoute = matchRoutes([{path:'/faculty/courses/:courseId'}], '/faculty/courses/17');
assert.equal(facultyCourseRoute[0].params.courseId, '17');
assert.equal(matchRoutes([{path:'/faculty/courses/:courseId'}], '/student/courses/17'), null);
const studentCourseRoute = matchRoutes([{path:'/student/courses/:courseId'}], '/student/courses/17');
assert.equal(studentCourseRoute[0].params.courseId, '17');
assert.equal(matchRoutes([{path:'/student/courses/:courseId'}], '/faculty/courses/17'), null);
const groupedStudentMaterials = studentMaterialGroups([
  {id:1,material_type:'notes'}, {id:2,material_type:'pyq'}, {id:3,material_type:'exam'},
]);
assert.deepEqual(groupedStudentMaterials.notes.map(item => item.id), [1]);
assert.deepEqual(groupedStudentMaterials.pyqs.map(item => item.id), [2]);
assert.deepEqual(groupedStudentMaterials.other.map(item => item.id), [3]);
console.log('PASS separate student course route and course-specific notes, PYQ and other-material grouping');
const programmingRoute = matchRoutes([{path:'/student/programming-assessments/:assessmentId'}], '/student/programming-assessments/21');
assert.equal(programmingRoute[0].params.assessmentId, '21');
assert.ok(dashboardNavigation.student.some(item => item.id === 'programming-assessments'));
const programmingBuilder = renderToStaticMarkup(<ProgrammingAssessmentForm course={{id:7,name:'Specific course'}} onCreated={() => {}} />);
assert.ok(programmingBuilder.includes('Publish programming assessment'));
assert.ok(programmingBuilder.includes('Hide this test case from students'));
assert.ok(programmingBuilder.includes('Python 3') && programmingBuilder.includes('JavaScript'));
console.log('PASS programming-assessment route, navigation and faculty builder rendering');
console.log(`PASS ${count} page URLs, sidebar links, active state, headings, and role-specific route matching`);
const onboarding = renderToStaticMarkup(<StaticRouter location="/register-institution"><InstitutionRegistration /></StaticRouter>);
for (const text of ['Institution details', 'Administrator profile', 'Official institution email', 'Logo', 'Create institution and administrator']) {
  assert.ok(onboarding.toLowerCase().includes(text.toLowerCase()), text);
}
assert.ok(onboarding.includes('minLength="12"'));
assert.ok(onboarding.includes('href="/login"'));
assert.ok(onboarding.includes('not automatically verified'));
assert.ok(onboarding.includes('type="file"'));
assert.ok(onboarding.includes('accept="image/png,image/jpeg,image/webp"'));
assert.ok(onboarding.includes('Choose logo image'));
assert.ok(onboarding.includes('Or use a hosted HTTPS logo URL'));
for (const accountType of ['student', 'faculty', 'hod']) {
  const html = renderToStaticMarkup(<AccountRegistrationForm accountType={accountType} departments={[{id: 1, name: 'Isolated test department'}]} onCreated={() => {}} />);
  assert.ok(html.includes('<select') && html.includes('Isolated test department'));
  assert.ok(html.includes('type="password"'));
  assert.ok(html.includes(`id="register-${accountType}"`));
  if (accountType === 'hod') assert.ok(html.includes('cannot administer accounts'));
  if (accountType === 'student') {
    for (const label of ['Registration / roll number', 'Program', 'Batch', 'Current semester', 'Section']) assert.ok(html.includes(label));
    assert.ok(html.includes('Semester 8 · Year 4'));
  }
  if (accountType !== 'student') assert.ok(html.includes('Official employee ID'));
}
const emptyForm = renderToStaticMarkup(<AccountRegistrationForm accountType="hod" departments={[]} onCreated={() => {}} />);
assert.ok(emptyForm.includes('disabled=""'));
assert.ok(emptyForm.includes('Create a department first'));
const editor = renderToStaticMarkup(<AccountEditor account={{id: 1, name: 'Isolated test', role: 'hod', email: 'test@example.com', department: 'CS'}} departments={[{id:1,name:'CS'}]} onSaved={() => {}} onCancel={() => {}} />);
assert.ok(editor.includes('Save account'));
assert.ok(!editor.includes('name="role"') && !editor.includes('name="institution_id"'));
console.log('PASS institution onboarding, role-specific account forms, department selection and safe account editor rendering');
const erpIntegration = renderToStaticMarkup(<ERPIntegration />);
assert.ok(dashboardNavigation.admin.some(item => item.id === 'erp'));
for (const text of ['ERP integration', 'ERP HTTPS base URL', 'ERP API token', 'Import ERP user directory', 'Preview ERP users', 'Sync courses &amp; attendance', 'Recent ERP syncs', 'No sample events are created']) assert.ok(erpIntegration.includes(text));
assert.ok(erpIntegration.includes('type="password"'));
const erpPreview = renderToStaticMarkup(<ERPUserImportPreview busy={false} onConfirm={() => {}} onCancel={() => {}} preview={{expires_in_minutes:15,creates:2,updates:1,skipped:1,records:[{row:1,role:'faculty',institutional_id:'EMP-1',name:'ERP Faculty',email:'faculty@college.edu',department:'CS',action:'create',reason:null},{row:2,role:'admin',institutional_id:'ADM-1',name:'ERP Admin',email:'admin@college.edu',department:null,action:'skip',reason:'Administrator accounts cannot be imported from an ERP'}]}} />);
for (const text of ['Administrator confirmation required', 'ERP user import preview', 'Confirm user import', 'ERP Faculty', 'Administrator accounts cannot be imported']) assert.ok(erpPreview.includes(text));
console.log('PASS administrator ERP configuration, reviewed role import, encrypted-token input, sync actions and honest empty state');
for (const role of ['admin', 'faculty', 'hod', 'student']) assert.ok(dashboardNavigation[role].some(item => item.id === 'ai-assistant'));
const aiAction = renderToStaticMarkup(<ActionCard action={{id:1,intent:'schedule_class',status:'draft',prompt:'Schedule CS401 tomorrow at 10 AM',confidence:.93,requires_confirmation:true,preview:{course:'Cloud Computing',published:false}}} busy={false} onConfirm={() => {}} onReject={() => {}} onCorrect={() => {}} />);
assert.ok(aiAction.includes('Confirm action') && aiAction.includes('Reject') && aiAction.includes('Intent confidence 93%'));
assert.ok(aiAction.includes('AI understood this incorrectly'));
const bulkCsv = 'role,name,email,institutional_id,department,program,batch,semester_number,section\nstudent,"Learner, One",learner@college.edu,S-1,CS,B.Tech,2026-2030,1,A\nfaculty,Faculty One,faculty@college.edu,F-1,CS,,,,';
const parsedBulk = parseBulkCsv(bulkCsv);
assert.equal(parsedBulk.length, 2);
assert.equal(parsedBulk[0].name, 'Learner, One');
assert.equal(parsedBulk[0].semester_number, 1);
assert.equal(parsedBulk[1].semester_number, null);
assert.throws(() => parseBulkCsv('name,email\nTest,test@example.edu'), /Missing CSV columns/);
const bulkPanel = renderToStaticMarkup(<BulkAccountsPanel busy={false} onPreview={() => {}} />);
assert.ok(bulkPanel.includes('Bulk account builder') && bulkPanel.includes('Account CSV') && bulkPanel.includes('Passwords are not accepted'));
assert.ok(bulkPanel.includes('Download CSV template') && bulkPanel.includes('download="ekeekrta-account-import-template.csv"'));
assert.equal(bulkCsvTemplate, 'role,name,email,institutional_id,department,program,batch,semester_number,section\r\n');
const forgotPassword = renderToStaticMarkup(<StaticRouter><ForgotPasswordPage /></StaticRouter>);
assert.ok(forgotPassword.includes('Reset your password') && forgotPassword.includes('Send reset link') && forgotPassword.includes('href="/login"'));
const resetPassword = renderToStaticMarkup(<StaticRouter location="/reset-password?token=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_123456"><ResetPasswordPage /></StaticRouter>);
assert.ok(resetPassword.includes('Choose a new password') && resetPassword.includes('minLength="12"') && resetPassword.includes('Reset password'));
const contentPanel = renderToStaticMarkup(<FacultyContentDraftPanel courses={[{id: 1, code: 'CS401', name: 'Cloud Computing'}]} busy={false} onPreview={() => {}} />);
for (const text of ['Lesson-note content studio', 'Faculty lesson notes', 'Generate review draft', 'Quiz with answer key', 'CS401 · Cloud Computing']) assert.ok(contentPanel.includes(text));
assert.ok(contentPanel.includes('minLength="80"') && contentPanel.includes('maxLength="12000"'));
const knowledgeFaculty = renderToStaticMarkup(<CourseKnowledgePanel role="faculty" courses={[{id:1,code:'CS401',name:'Cloud Computing'}]} />);
for (const text of ['Course knowledge assistant', 'Approved course text', 'Add approved source', 'Find a cited answer', 'CS401 · Cloud Computing']) assert.ok(knowledgeFaculty.includes(text));
const knowledgeStudent = renderToStaticMarkup(<CourseKnowledgePanel role="student" courses={[{id:1,code:'CS401',name:'Cloud Computing'}]} />);
assert.ok(knowledgeStudent.includes('Find a cited answer'));
assert.ok(!knowledgeStudent.includes('Add approved source'));
const facultyLecture = renderToStaticMarkup(<LectureNotesPanel courseId={1} sessions={[{id:4,ended_at:'2026-09-15T10:00:00Z'}]} manager />);
for (const text of ['Lecture summaries', 'Verified lecture transcript', 'Prepare review draft', 'does not currently deliver recordings', 'Private class recordings', 'institution-reviewed EKEEKRTA model executable']) assert.ok(facultyLecture.includes(text));
const studentLecture = renderToStaticMarkup(<LectureNotesPanel courseId={1} sessions={[]} />);
assert.ok(studentLecture.includes('Faculty has not published lecture notes'));
assert.ok(!studentLecture.includes('Verified lecture transcript'));
assert.ok(!studentLecture.includes('Private class recordings'));
assert.equal(preparationLabel({status:'uploaded'}), 'recording uploaded; preparation not requested');
assert.equal(preparationLabel({status:'preparation_queued',preparation:{status:'queued'}}), 'queued for the private institution worker');
assert.equal(preparationLabel({status:'preparing_media',preparation:{status:'processing'}}), 'private worker is preparing audio and frames');
assert.equal(preparationLabel({status:'preparation_failed',preparation:{status:'failed',error_code:'recording_integrity_failed'}}), 'processing failed (recording_integrity_failed)');
assert.ok(preparationLabel({status:'media_prepared'}).includes('transcription model not connected'));
assert.ok(preparationLabel({status:'transcript_draft_ready'}).includes('ready for faculty review'));
const draftReview = renderToStaticMarkup(<LectureReviewControls lecture={{id:1,status:'draft',summary:{summary:'Source statement',notes:[{statement_number:1,text:'Source statement'}],candidate_notes:[{statement_number:1,text:'Source statement'}],topics:['course'],candidate_topics:['course']}}} busy={false} onReview={() => {}} onEdit={() => {}} onPublication={() => {}} />);
for (const text of ['Approve transcript statements', 'Exclude anything inaccurate or sensitive', 'Save reviewed selection', 'Correct transcript']) assert.ok(draftReview.includes(text));
assert.ok(!draftReview.includes('Publish approved notes'));
const reviewedReview = renderToStaticMarkup(<LectureReviewControls lecture={{id:1,status:'reviewed',summary:{summary:'Approved statement',notes:[{statement_number:1,text:'Approved statement'}],candidate_notes:[{statement_number:1,text:'Approved statement'}],topics:[],candidate_topics:[]}}} busy={false} onReview={() => {}} onEdit={() => {}} onPublication={() => {}} />);
assert.ok(reviewedReview.includes('Publish approved notes'));
assert.ok(!reviewedReview.includes('Save your changed selection before publishing.'));
const cgpaPanel = renderToStaticMarkup(<CgpaPlannerPanel busy={false} onPlan={() => {}} onRefreshERP={() => {}} gradingScale={10} passingGrade={4} courses={[{id:1,code:'CS401',name:'Cloud Computing',course_type:'academic',credits:4}]} latestPlan={{result:{projection:{status:'challenging',explanation:'Test projection',required_average_for_remaining_credits:8.5,best_possible_final_cgpa:9.1,total_credits_at_goal:160,milestones:[{remaining_semester:1,planned_sgpa:8.5,projected_cgpa:7.7}]},course_scenario:{scenario_credits:4,projected_cgpa_after_scenario:7.4,courses:[{course_id:1,course_code:'CS401',course:'Cloud Computing',credits:4,expected_grade_point:9,quality_points:36}]},course_priorities:[{course_id:1,course_code:'CS401',course:'Cloud Computing',weekly_hours:6,evidence:['Attendance: 72%'],recommended_actions:['Attend upcoming classes.']}],roadmap:['Review every week.'],official_record_notice:'This is not an official result.',external_model:false}}} />);
for (const text of ['Target CGPA planner', 'Stage 2', 'Institution grading scale', 'Current-course grade scenario', 'What-if result', 'Current official CGPA', 'Credits still remaining', 'Create my roadmap', 'Challenging', 'Cloud Computing', 'not an official result']) assert.ok(cgpaPanel.includes(text));
const progressPanel = renderToStaticMarkup(<ProgressInsightsPanel role="faculty" courses={[{id:1,code:'CS401',name:'Cloud Computing'}]} autoLoad={false} initialData={{scope:{result_limited:false},summary:{total_students:1,critical:1,high:0,watch:0,stable:0,insufficient_data:0},students:[{student_id:3,student:'Student One',institutional_id:'S-1',department:'CS',risk_level:'critical',risk_reasons:['Attendance is 50%, below the critical 60% threshold.'],recommended_actions:['Make an attendance recovery plan.'],metrics:{attendance:{percent:50,attended:1,held:2},performance_average_percent:45,performance_evidence_count:2,assignments:{missing_due:2,submitted:1,total:3}},courses:[{course_id:1,course_code:'CS401',course_name:'Cloud Computing',risk_level:'critical',attendance:{percent:50},performance_average_percent:45,assignments:{missing_due:2}}]}],notice:'This is not an official grade.',data_basis:'Current records.',external_model:false}} />);
for (const text of ['Native AI Stage 5', 'Progress intelligence', 'Explainable', 'Student One', 'Critical support', 'Why this is flagged', 'Recommended next actions', 'CS401 · Cloud Computing', 'not an official grade']) assert.ok(progressPanel.includes(text));
assert.ok(dashboardNavigation.admin.some(item => item.id === 'ai-review'));
console.log('PASS native AI actions, Stage 5 progress intelligence, cited course assistant, reviewable lecture notes, CSV validation and correction consent');
assert.equal(brand.name, 'EKEEKRTA');
assert.equal(pageTitle('Sign in'), 'Sign in · EKEEKRTA');
assert.equal(pageTitle('Courses', 'Test Institution'), 'Courses · Test Institution · EKEEKRTA');
assert.equal(pageTitle('EKEEKRTA'), 'EKEEKRTA');
const logo = renderToStaticMarkup(<BrandLogo />);
assert.ok(logo.includes('EKEEKRTA') && logo.includes('/brand-mark.svg'));
const login = renderToStaticMarkup(<ThemeProvider><AuthProvider><StaticRouter location="/login"><Login /></StaticRouter></AuthProvider></ThemeProvider>);
assert.ok(login.includes('EKEEKRTA') && login.includes('type="password"'));
assert.ok(login.includes('href="/register-institution"'));
assert.ok(login.includes('Google college account sign-in'));
assert.ok(renderToStaticMarkup(<GoogleSignIn onCredential={() => {}} />).includes('Loading Google sign-in'));
assert.ok(!login.includes('LMS Platform') && !login.includes('Smart Virtual Learning'));
assert.ok(onboarding.includes('EKEEKRTA'));
const institutionShell = renderToStaticMarkup(<StaticRouter location="/student"><DashboardShell user={{name:'Isolated test',role:'student',institution:{name:'Independent Institution',logo_url:'https://example.com/institution.svg'}}} title="Student Hub" roleLabel="Student" onLogout={() => {}}><p>Own dashboard</p></DashboardShell></StaticRouter>);
assert.ok(institutionShell.includes('Independent Institution'));
assert.ok(institutionShell.includes('https://example.com/institution.svg'));
assert.ok(institutionShell.includes('alt="Independent Institution logo"'));
assert.ok(institutionShell.includes('EKEEKRTA'));
const institutionFallbackShell = renderToStaticMarkup(<StaticRouter location="/student"><DashboardShell user={{name:'Isolated test',role:'student',institution:{name:'Independent Institution',logo_url:null}}} title="Student Hub" roleLabel="Student" onLogout={() => {}}><p>Own dashboard</p></DashboardShell></StaticRouter>);
assert.ok(institutionFallbackShell.includes('institution-fallback-logo') && institutionFallbackShell.includes('>II<'));
assert.ok(!institutionFallbackShell.includes('portal-brand-mark'));
console.log('PASS EKEEKRTA wordmark, sign-in branding, page titles and separate institution identity');
globalThis.window = { location: { hostname: 'ekeekrta.alpha.edu' } };
const institutionLogin = renderToStaticMarkup(<ThemeProvider><AuthProvider><StaticRouter location="/login"><Login /></StaticRouter></AuthProvider></ThemeProvider>);
assert.ok(institutionLogin.includes('ekeekrta.alpha.edu'));
assert.ok(institutionLogin.includes('Loading your institution'));
assert.ok(!institutionLogin.includes('type="password"'));
assert.ok(!institutionLogin.includes('href="/register-institution"'));
assert.ok(!institutionLogin.includes('Google college account sign-in'));
delete globalThis.window;
console.log('PASS institution portal waits for verified configuration before showing login and hides onboarding');
assert.equal(institutionHost('localhost'), null);
assert.equal(institutionHost('smart-virtual-lms-frontend-ruby.vercel.app'), null);
assert.equal(institutionHost('ekeekrta.vercel.app'), null);
assert.equal(institutionHost('EKEEKRTA.HITAM.ORG'), 'ekeekrta.hitam.org');
assert.equal(institutionHost('ekeekrta.unknown.edu'), 'ekeekrta.unknown.edu');
assert.equal(institutionHost('ekeekrta-platform.vercel.app'), null);
assert.deepEqual(institutionHeaders(), {});
(async () => {
  const previousFetch = globalThis.fetch;
  const calls = [];
  globalThis.window = { location: { hostname: 'ekeekrta.alpha.edu' } };
  globalThis.localStorage = { getItem: () => 'isolated-test-token' };
  globalThis.fetch = async (url, options) => { calls.push({url, options}); return {ok: true, status: 200, json: async () => ({})}; };
  try {
    await apiFetch('/auth/me', {headers: {'X-Institution-Host': 'ekeekrta.beta.edu'}});
    await requestLogin('isolated@alpha.edu', 'unused-test-password');
    await createFaculty({});
    const multipart = new FormData(); multipart.append('permissions_confirmed', 'true');
    await apiFetch('/ai/lectures/sessions/4/recording', {method:'POST', body:multipart});
    assert.equal(calls.at(-1).options.headers['Content-Type'], undefined);
    for (const call of calls) assert.equal(call.options.headers['X-Institution-Host'], 'ekeekrta.alpha.edu');
    assert.equal(calls[0].options.headers.Authorization, 'Bearer isolated-test-token');
    globalThis.window.location.hostname = 'localhost';
    await requestLogin('isolated@alpha.edu', 'unused-test-password');
    assert.equal(calls.at(-1).options.headers['X-Institution-Host'], undefined);
    console.log('PASS API requests derive institution context from the hostname; main-site login stays generic');
    const scripts = [];
    globalThis.document = { createElement: () => ({remove() { this.removed = true; }}), head: {appendChild(script) { scripts.push(script); }} };
    const first = loadGoogleIdentity();
    assert.equal(loadGoogleIdentity(), first);
    assert.equal(scripts[0].src, 'https://accounts.google.com/gsi/client');
    scripts[0].onerror();
    await assert.rejects(first, /could not load/);
    assert.equal(scripts[0].removed, true);
    const retry = loadGoogleIdentity();
    const googleApi = { initialize() {}, renderButton() {} };
    globalThis.window.google = { accounts: { id: googleApi } };
    scripts[1].onload();
    assert.equal(await retry, googleApi);
    assert.equal(await loadGoogleIdentity(), googleApi);
    assert.equal(scripts.length, 2);
    console.log('PASS Google script loading deduplication, load failure, cleanup and retry (non-browser unit check)');
  } finally {
    globalThis.fetch = previousFetch;
    delete globalThis.window;
    delete globalThis.localStorage;
    delete globalThis.document;
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
